# Generated by Django 5.2.7 on 2025-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='uploads/audio/')),
                ('skill_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('midi_file', models.FileField(blank=True, null=True, upload_to='uploads/midi/')),
                ('sheet_music', models.FileField(blank=True, null=True, upload_to='uploads/sheet_music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
