import os
import warnings
import torch
from music21 import converter
from django.conf import settings
from basic_pitch.inference import predict_and_save
from basic_pitch import ICASSP_2022_MODEL_PATH

from .model import SeqSimplifier
from .utils import midi_to_pianoroll, pianoroll_to_midi, add_difficulty_channel, overallComplexity

warnings.filterwarnings('ignore', category=UserWarning, module='resampy')
os.environ["BASIC_PITCH_BACKEND"] = "CoreML"
audio_path = "Users/sudhirghanate/Downloads/sampleaudio.mp3"


def audio_to_midi(audio_path, output_midi_path):
    if not os.path.exists(audio_path):
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    os.makedirs(os.path.dirname(output_midi_path), exist_ok=True)

    predict_and_save(
        [audio_path],
        os.path.dirname(output_midi_path),
        save_midi=True,
        sonify_midi=False,
        save_model_outputs=False,
        save_notes=False,
        model_or_model_path=str(ICASSP_2022_MODEL_PATH)
    )

    generated_files = [f for f in os.listdir(os.path.dirname(output_midi_path)) if f.endswith('.mid')]
    if not generated_files:
        raise FileNotFoundError("MIDI file not generated by Basic Pitch")

    os.rename(
        os.path.join(os.path.dirname(output_midi_path), generated_files[0]),
        output_midi_path
    )

  audio_to_midi(audio_path, output_midi_path)