import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import warnings
import torch
from music21 import converter
from django.conf import settings
from basic_pitch.inference import predict_and_save
from basic_pitch import ICASSP_2022_MODEL_PATH
os.environ['DJANGO_SETTINGS_MODULE'] = 'myproject.settings'
import django
django.setup()



warnings.filterwarnings('ignore', category=UserWarning, module='resampy')
os.environ["BASIC_PITCH_BACKEND"] = "CoreML"
audio_path = "/Users/sudhirghanate/Downloads/sampleaudio.mp3"


def audio_to_midi(audio_path, output_midi_path):
    if not os.path.exists(audio_path):
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    os.makedirs(os.path.dirname(output_midi_path), exist_ok=True)

    predict_and_save(
        [audio_path],
        os.path.dirname(output_midi_path),
        save_midi=True,
        sonify_midi=False,
        save_model_outputs=False,
        save_notes=False,
        model_or_model_path=str(ICASSP_2022_MODEL_PATH)
    )

    generated_files = [f for f in os.listdir(os.path.dirname(output_midi_path)) if f.endswith('.mid')]
    if not generated_files:
        raise FileNotFoundError("MIDI file not generated by Basic Pitch")

    os.rename(
        os.path.join(os.path.dirname(output_midi_path), generated_files[0]),
        output_midi_path
    )

audio_to_midi("/Users/sudhirghanate/Downloads/sampleaudio.mp3", '~/Downloads/sampleaudio.mid')

def convert_audio_sheet(output_midi_path):
    if not os.path.exists(output_midi_path):
        raise FileNotFoundError(f"MIDI file not found: {output_midi_path}")
    
    base = os.path.splitext(os.path.basename(output_midi_path))[0]
    sheet_dir = os.path.join(settings.MEDIA_ROOT, 'uploads', 'sheet_music')
    os.makedirs(sheet_dir, exist_ok=True)

    midi_out = os.path.join(sheet_dir, f"{base}.mid")
    xml_out = os.path.join(sheet_dir, f"{base}.musicxml")
    
    score = converter.parse(output_midi_path)
    score.write('musicxml', fp=xml_out)

    return {
        "midi_file": midi_out,
        "xml": xml_out,
    }
print(convert_audio_sheet('~/Downloads/sampleaudio.mid'))

